steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/project3-369120/project3:$COMMIT_SHA', './server']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/project3-369120/project3:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'project3'
  - '--image'
  - 'gcr.io/project3-369120/project3:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
images:
 - 'gcr.io/project3-369120/project3:$COMMIT_SHA'